name: 'semantic-release action'
description: 'Action to run semantic-release with deps for sitkoru/semantic-release-config preinstalled'
inputs:
  semantic-release-version:
    description: 'semantic-release version'
    required: true
    default: '17'
runs:
  using: "composite"
  steps:
    - name: Install node.js
      uses: actions/setup-node@v2.4.0
      with:
        node-version: "16"
    - name: Run semantic-release
      run: npx --package @sitkoru/semantic-release-config --package @semantic-release/changelog --package @semantic-release/git --package semantic-release@17 -y semantic-release
      shell: bash